<a href="https://colab.research.google.com/github/ShivaKumar8037/Gitam-Python/blob/master/13_7_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Transforming Code into Idiomatic  Python
- Replace traditional index manupulation with  Python  core looping idiomatic

In [0]:
#Looping over a range of numbers - Traditional approach
for i in [0,1,2,3,4,5]:
  print(i**2,end=" ")

0 1 4 9 16 25 

In [0]:
#Idiomatic Programming
for i in range(6):
  print(i**2,end=" ")

0 1 4 9 16 25 

### Looping Over a Collection 

In [0]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
  print(colors[i],end=" ")

red green yellow purple 

In [0]:
#idiomatic Approach
for color in colors:
  print(color,end = " ")

red green yellow purple 

###Looping backwards

In [0]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
  print(colors[i],end=" ")

purple yellow green red 

In [0]:
#idiomatic Approach
for color in reversed(colors):
  print(color,end = " ")

purple yellow green red 

###Looping in Sorted List

In [0]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
  print(color,end=" ")

green purple red yellow 

In [0]:
colors = ['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
  print(color,end=" ")

yellow red purple green 

###
- if x<=y and y<=z:
- if x<=y<=z: #idiomatic approach
- if x==True
- if x: #idiomatic approach

###Pandas

In [0]:
import pandas as pd

In [0]:
dt={'Id':[11,12,13,14,15],
'first_name':['A','B','C','D','E'],
'company':['aa','bb','cc','dd','ee'],
'Address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)  

In [0]:
print(mydt)

   Id first_name company Address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [0]:
import os 

In [0]:
os.chdir("D:\\MyData\\")#saves to certain location

In [0]:
mydt.to_csv("WorkingFile.csv",index=False)

###Reaing the data from CSV file

In [0]:
mydata= pd.read_csv('WorkingFile.csv')

In [0]:
print(mydata)

   Id first_name company Address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [0]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=1,names=["CustId","Name","Company","Address"])

In [0]:
print(mydata1)

   CustId Name Company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [0]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],names=["CustId","Name","Company","Address"])

In [0]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first_name  company  Address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


In [0]:
pwd

'/content'

###Print Only Two columns
###Print the large value from CustID column --max
###Print the least value from the CustID column -- min
###Average of CustID column --sum(li)/len(li)

In [0]:
d={'first_name':['A','B','C','D','E'],
'CustId':[11,12,13,14,15]}
myData = pd.DataFrame(d)  
print(myData)
CustId=[11,12,13,14,15]
print("Max of Customer Id:",max(CustId))
print("Min of Customer Id:",min(CustId))
print("Average of Customer Id:",sum(CustId)/len(CustId))

  first_name  CustId
0          A      11
1          B      12
2          C      13
3          D      14
4          E      15
Max of Customer Id: 15
Min of Customer Id: 11
Average of Customer Id: 13.0


###Numpy Package - Working with Multi Dimensional array
- Numpy array is a bit like Python List
- Numpy array is data structure of Numpy Lib
- It's short name for Numberic Python or Numerical **Python**

In [0]:
import numpy as np #Import the numpy package

In [0]:
li = [1,2,3,4,5]
print(li,end= " ")

[1, 2, 3, 4, 5] 

In [0]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)#2,3 where 2->rows of array and 3->cols of array
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
array = np.array(li)#used to convert list  to array using "np.array()"
print(array)

[1 2 3 4 5]


In [0]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)#reshapes array into 3 rows and two cols

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2))) # is used to stack the sequence of input arrays vertically to make a single array.

[[1 2 3]
 [4 5 6]]
